S05 us55 display members
WildCodeSchool/202302-orleans-php-project-inovin pull request #101
Opened 2023-07-05 07:53 UTC by Mikazian

2023-07-05 07:55 UTC, No3ml3 approved these changes

2023-07-05 09:45 UTC, sblondeau requested changes

2023-07-05 09:45 UTC, sblondeau commented on src/Controller/admin/AdminUserController.php
> +            'users' => $userRepository->findAll(),
order by lastname / firstname peut etre?

2023-07-05 14:46 UTC, Zakari-B requested changes

2023-07-05 14:46 UTC, Zakari-B commented on src/DataFixtures/UserFixtures.php
> +            $member->setZipCode('99999');
$member->setZipCode($faker->postcode())

(Avec la modif de mon autre commentaire sur le Facotry en fr_FR pour avoir la localisation française des CP.)

2023-07-05 14:46 UTC, Zakari-B commented on src/DataFixtures/UserFixtures.php
>          $faker = Factory::create();
$faker = Factory::create('fr_FR');

2023-07-05 14:46 UTC, Zakari-B commented on templates/admin/user/show.html.twig
> +                <th>Password</th>
Même l'admin ne devrait pas avoir les password affichés sur son espace.

Pensez à traduire aussi tous les champs sur cette page, elle fait partie de l'US courante.

2023-07-06 06:05 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-07-06 09:21 UTC, sblondeau approved these changes

2023-07-06 09:21 UTC, merged