S05 us24 service dosage
WildCodeSchool/202302-orleans-php-project-inovin pull request #110
Opened 2023-07-06 12:45 UTC by BENJAMIN-SAUSSAYE

2023-07-06 12:45 UTC, Abecker37 approved these changes

2023-07-06 15:06 UTC, sblondeau requested changes

2023-07-06 15:06 UTC, sblondeau commented on src/Service/CalculateWineDosageService.php
> +
et a priori on peut faire un array_column sur un prop d'objets dans un array (voir doc)

2023-07-06 15:06 UTC, sblondeau commented on src/Service/CalculateWineDosageService.php
> +        }
je ferais plutot un tableau qui au final devrait être
$result[] = ['dosage' => xxx, 'tastingSheet' => $tastingSheet];

avec $tastingSheet l'objet directement

2023-07-06 15:06 UTC, sblondeau commented on src/Service/CalculateWineDosageService.php
> +        return $ordonedArray;
faire une constante
const DOSAGES = [150, 50, 25];

puis ici 
```
foreach($ordonnedArray as $key => $value) {
  $results[] = ['dosage' => self::DOSAGES[$key], 'tasting' => $value]
}
```

2023-07-07 14:02 UTC, ElBarto444 approved these changes

2023-07-07 15:26 UTC, sblondeau approved these changes

2023-07-07 15:26 UTC, merged