Fixe css
WildCodeSchool/202302-orleans-php-project-inovin pull request #112
Opened 2023-07-06 15:24 UTC by Mikazian

2023-07-06 15:28 UTC, sblondeau requested changes

2023-07-06 15:28 UTC, sblondeau commented on templates/components/session/_opened_sessions.html.twig
> +				<div class="col-12 col-sm">
pas de col-12 c'est déjà par défaut, à enlever partout

2023-07-06 15:28 UTC, sblondeau commented on templates/components/session/_opened_sessions.html.twig
> +				<div class="col px-3 px-sm-4">
pas de padding/margin horizontal sur le meme niveau qu'une col
et pourquoi juste col ? col-unevaleur plutot ?

2023-07-07 07:37 UTC, Mikazian commented on templates/components/session/_opened_sessions.html.twig
> +				<div class="col-12 col-sm">
fait

2023-07-07 08:47 UTC, closed without merging