recipe index
WildCodeSchool/202302-orleans-php-project-inovin pull request #123
Opened 2023-07-10 07:53 UTC by Abecker37

2023-07-10 07:55 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-07-10 08:57 UTC, sblondeau requested changes

2023-07-10 08:57 UTC, sblondeau commented on templates/recipe/index.html.twig
> +                            {% set width = (itemTastingSheet.dosage ?? '0' * 100) / 250 %}
tu passes un containerReference, tu dois pas l'utiliser ici ?
note que tu peux aussi acceder direct à la constance depuis twig

2023-07-10 08:57 UTC, sblondeau commented on src/DataFixtures/RecipeFixtures.php
> +        $decallageId = 0;
decallage ça fait pas très anglais :p

2023-07-10 09:13 UTC, Mikazian approved these changes

2023-07-10 13:09 UTC, sblondeau approved these changes

2023-07-11 18:20 UTC, Mikazian approved these changes

2023-07-11 22:13 UTC, merged