created wine taste table and implemented it
WildCodeSchool/202302-orleans-php-project-inovin pull request #129
Opened 2023-07-10 15:32 UTC by ElBarto444

2023-07-11 18:23 UTC, Mikazian approved these changes

2023-07-11 22:17 UTC, sblondeau requested changes

2023-07-11 22:17 UTC, sblondeau commented on src/Form/WineType.php
> +                    'by_reference' => true,
pas la peine le by_reference

2023-07-12 08:13 UTC, sblondeau approved these changes

2023-07-12 08:13 UTC, merged