S01 us04 home
WildCodeSchool/202302-orleans-php-project-inovin pull request #13
Opened 2023-06-08 12:43 UTC by Abecker37

2023-06-08 13:32 UTC, Zakari-B requested changes

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +			<img class="object-fit-cover img-fluid w-100 " src="{{ asset('build/images/vine.webp') }}" alt="">
Pour l'accessibilité, on ne mets jamais de alt vides.

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +			<h1 class="size-inovin text-center ">INO VIN</h1>
Espace inutile.

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +			{% include "./icones/surlignage.svg" %}
./ inutile.

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +				recette de vin, que nous nous ferons un plaisir de l'élaborer pour vous.
d'élaborer

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +	<h2 class="text-primary-light fw-light mt-5"> {% include './icones/decoration.svg' %}DÉCOUVREZ TOUTES LES ÉTAPES
./ inutile ici aussi

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +		{% include "./icones/surlignage_main.svg" %}
idem

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +			{% include './components/_pine-circle.html.twig' with {'pine_number':'1'} %}
idem

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +				<div class="fw-normal text-primary-light p-2">S’INSCRIRE SUR LE SITE</div>
Je pensais m'inscrire ailleurs, personnellement.

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +					Vous allez recevoir un mail de confirmation dans votre boîte mail.
Je pensais recevoir ce mail par la poste, on m'a menti.

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +					Consulter votre messagerie et cliquer sur le lien afin de valider votre
Consultez / Cliquez

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +					Consulter les séances disponibles dans votre espace personnel ou via
Consultez / le lieu et les horaires

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +					Pour participer à une séance, cliquer simplement sur <a class="text-primary-light text-decoration-none"
cliquez

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +			{% include './components/_pine-circle.html.twig' with {'pine_number':'5'} %}
./

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +					L’équipe fourniront des tablettes aux participants afin de remplir des
fournira / dégustation

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +				<div class="fw-normal text-primary-light p-2">REMPLIR LES FICHES DE DÉGUSTATIONS</div>
Dégustation

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +					en cours. Vous allez vous retrouvez avec 4 fiches de vins à remplir.
retrouver. Mais en dehors de la conjugaison je reformulerais même toute la phrase qui est très maladroite.

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +					Pas de panique, les fiches ont été conçues pour pour être facile à
pour en trop / faciles / votre en trop

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +			{% include './components/_pine-circle.html.twig' with {'pine_number':'6'} %}
./

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +					Lorsque vous aurez remplis les 4 fiches, vous obtiendrez votre propre
rempli

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +				Vous pouvez bien entendu, échanger vos découverte avec vos
pourrez

2023-06-08 13:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +					Vous aurez la possibilité de commander votre bouteille et repartir
Acheter alors, parce qu'une commande sous entend que ce ne sera pas disponible de suite.

2023-06-08 13:32 UTC, Zakari-B commented on assets/styles/home.scss
> +    height:100vh;
Un header de 100vh est-il vraiment un header ?

2023-06-08 21:07 UTC, sblondeau requested changes

2023-06-08 21:07 UTC, sblondeau commented on assets/app.js
> +
ligne en plus inutile dans ce fichier qui ne devrait pas etre visible dans cette PR

2023-06-08 21:07 UTC, sblondeau commented on templates/home/index.html.twig
> +			{% include "./icones/surlignage.svg" %}
+1

2023-06-08 21:07 UTC, sblondeau commented on templates/home/index.html.twig
> +					Vous allez recevoir un mail de confirmation dans votre boîte mail.
ahah il est taquin ! mais c'est vrai que les phrases sont pas forcément bien tournées ;-)

2023-06-08 21:46 UTC, No3ml3 approved these changes

2023-06-09 06:48 UTC, sblondeau requested changes

2023-06-09 06:48 UTC, sblondeau commented on templates/home/index.html.twig
> +				<div class="fw-normal text-primary-light p-2">S’INSCRIRE SUR LE SITE</div>
mettre S'INSCRIRE suffit
ou "CREER UN COMPTE" comme tu veux

2023-06-09 07:34 UTC, No3ml3 approved these changes

2023-06-09 07:46 UTC, sblondeau approved these changes

2023-06-09 07:46 UTC, merged