S01 u13 sessions Read part of crud
WildCodeSchool/202302-orleans-php-project-inovin pull request #17
Opened 2023-06-09 08:01 UTC by ElBarto444

2023-06-09 08:08 UTC, No3ml3 approved these changes

2023-06-09 08:41 UTC, sblondeau requested changes

2023-06-09 08:41 UTC, sblondeau commented on src/Controller/SessionController.php
> +            'sessions' => $sessionRepository->findAll(),
trier par date desc ?

2023-06-09 08:41 UTC, sblondeau commented on templates/session/index.html.twig
> +				{% for session in sessions|sort((a, b) => b.openingDate <=> a.openingDate) %}
ah tu fais le tri là ? moins performant que de le faire coté bdd directement

2023-06-09 08:41 UTC, sblondeau commented on templates/session/index.html.twig
> +						<td colspan="2">aucuns enregistrements trouvés</td>
aucun enregistrement trouvé
tu en as pas, donc pas de s ;-)

2023-06-09 09:18 UTC, No3ml3 approved these changes

2023-06-09 10:22 UTC, Zakari-B requested changes

2023-06-09 10:22 UTC, Zakari-B commented on templates/session/show.html.twig
> +                <th>Name</th>
En français. Ca ne me choque pas que le new.html.twig par exemple reste en anglais (puisqu'il est dans le Create du CRUD), mais le show fait partie du de ton US Read, donc ce fichier doit être terminé (et de fait, traduit).

2023-06-09 10:22 UTC, Zakari-B commented on src/Form/SessionType.php
> +            ->add('name')
Il faut typer le formbuilder.

2023-06-09 10:22 UTC, Zakari-B commented on src/DataFixtures/SessionFixtures.php
> +            $session->setOpeningDate($faker->dateTimeThisYear($openingDate));
$session->setOpeningDate($faker->dateTimeThisYear(new DateTime()));

Puis la var openingDate à supprimer.

2023-06-13 05:42 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-06-13 06:55 UTC, sblondeau requested changes

2023-06-13 06:55 UTC, sblondeau commented on assets/styles/admin.scss
> +}
je ne sais pas trop ce que tu veux faire avec ça, mais c'est prefixé webkit, donc incompatible avec tous les navigateur (et j'ai vérifié, non fonctionnel sous firefox). Fais autrement pour etre plus standard ;-)

2023-06-13 06:55 UTC, sblondeau commented on src/Form/SessionType.php
> +            ->add('name')
à faire dans la US pour le Create ;-)

2023-06-13 06:55 UTC, sblondeau commented on templates/session/index.html.twig
> +							<a class="link-offset-2 px-1 mx-1" href="{{ path('app_session_edit', {'id': session.id}) }}">
idem

2023-06-13 06:55 UTC, sblondeau commented on templates/session/index.html.twig
> +							<a class="link-offset-2 px-1 mx-1" href="{{ path('app_session_show', {'id': session.id}) }}">
NON !!! pas de button dans un a ! ajouter les classes btn sur le a plutot

2023-06-13 06:55 UTC, sblondeau commented on templates/session/show.html.twig
> +{% extends 'admin.html.twig' %}
je pense que cette page est inutile ?  mais si vraiment vous voulez la garder, ça serait une autre US.
Le list et le show est différents

2023-06-13 06:55 UTC, sblondeau commented on migrations/Version20230608094805.php
> +        $this->addSql('CREATE TABLE session (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, opening_date DATETIME NOT NULL, description LONGTEXT DEFAULT NULL, closed TINYINT(1) NOT NULL,
tu devrais avoir un nouveau fichier de migration et non une ligne en plus au fichier existant, qui est renommé au passage... j'ai peur que ça vous fasse des conflits ou des pb au moment de jouer les migrations...

2023-06-14 07:58 UTC, No3ml3 approved these changes

2023-06-14 09:19 UTC, sblondeau approved these changes

2023-06-14 15:40 UTC, merged