Admin vin index
WildCodeSchool/202302-orleans-php-project-inovin pull request #23
Opened 2023-06-09 14:29 UTC by Abecker37

2023-06-09 14:51 UTC, No3ml3 approved these changes

2023-06-10 19:14 UTC, sblondeau requested changes

2023-06-10 19:14 UTC, sblondeau commented on src/Controller/WineController.php
> +            'wines' => $wineRepository->findAll(),
class par ordre alphab ?

2023-06-10 19:14 UTC, sblondeau commented on templates/wine/index.html.twig
> +                <td colspan="9">aucuns enregistrements trouvés</td>
singulier ! y en a AUCUN, pas plusieurs ;-)

2023-06-13 11:30 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-06-13 11:59 UTC, sblondeau requested changes

2023-06-13 11:59 UTC, sblondeau commented on src/Entity/Wine.php
> +    private ?float $price = null;
utiliser le type DECIMAL en bdd pour price et alcoholPercent
pour le volume, vous l'indiquerez en cl uniquement ? vu que vous avez un int ? mais meme dans ce cas c'est pas bon car vous ne gérer par les demi bouteilles à 37.5 cl :p donc float pour le coup

2023-06-13 14:36 UTC, Zakari-B requested changes

2023-06-13 14:36 UTC, Zakari-B commented on src/Entity/Wine.php
> +    private ?GrapeVariety $grapVariety = null;
il manque un e a grape

2023-06-13 14:36 UTC, Zakari-B commented on src/Entity/Wine.php
> +    private ?bool $isEnable = null;
Juste Enabled. Pas is (qui fait partie du nom du getter pour les booléens).

2023-06-13 14:36 UTC, Zakari-B commented on src/Entity/Wine.php
> +    private ?float $price = null;
Modif pas faite

2023-06-13 14:36 UTC, Zakari-B commented on migrations/Version20230613135104.php
> +        $this->addSql('ALTER TABLE wine CHANGE volume volume DOUBLE PRECISION NOT NULL, CHANGE alcohol_percent alcohol_percent NUMERIC(3, 1) NOT NULL');
Une seule migration par PR : ce fichier est a intégrer dans l'autre.

2023-06-13 14:36 UTC, Zakari-B commented on src/DataFixtures/WineFixtures.php
> +            $wine->setVolume($faker->numberBetween(3, true));
Pas au point ça... Il est en quoi le volume ? en cL ? Parce que ça me parait soit trop soit trop peu. Et la ça va donc de 3 à 1 puisque true = 1.

2023-06-13 14:36 UTC, Zakari-B commented on src/DataFixtures/WineFixtures.php
> +            $manager->persist($wine);
Le persist TOUJOURS en dernier élément de la boucle, après l'ajout de la référence.

2023-06-13 14:36 UTC, Zakari-B commented on templates/wine/index.html.twig
> +    Nos Vin
Vins, c'est du pluriel.

2023-06-13 14:36 UTC, Zakari-B commented on templates/wine/index.html.twig
> +                <td colspan="9">aucun enregistrement trouvé</td>
La ponctuation c'est bien : majuscule et point svp.

2023-06-13 14:36 UTC, Zakari-B commented on templates/wine/show.html.twig
L'index c'est le R du CRUD, le show c'est aussi le R du CRUD, donc ce fichier fait partie de cette US et doit être terminé, donc traduit, notamment.

2023-06-13 15:36 UTC, sblondeau approved these changes

2023-06-14 09:19 UTC, merged