fix country
WildCodeSchool/202302-orleans-php-project-inovin pull request #260
Opened 2023-07-25 15:07 UTC by Abecker37

2023-07-25 15:08 UTC, No3ml3 approved these changes

2023-07-25 17:32 UTC, sblondeau requested changes

2023-07-25 17:32 UTC, sblondeau commented on src/Form/RegistrationFormType.php
> +            ->add('country', CountryType::class, [
si tu passe sur un country type, faut modifier l'affichage dans twig pour qu'il transforme le code iso du pays en nom complet (y a un filtre twig pour ça)

2023-07-25 17:32 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +                    $form->get('password')->getData()
non justement normlement c'est bien plainPassword (le mot de passe en clair) et il faut modifier le registerType pour mettre plainPassword au lieu de password.
et là si le form est soumis, le plainpassword est hashé et setté dans le $password qui lui est relié à la bdd

2023-07-26 07:57 UTC, Abecker37 commented on src/Controller/RegistrationController.php
> +                    $form->get('password')->getData()
avec le password je l'ai hashé également et enregistrer en BDD

2023-07-26 08:17 UTC, Mikazian approved these changes

2023-07-26 08:20 UTC, sblondeau approved these changes

2023-07-26 08:20 UTC, merged