S02 us44 user gestion
WildCodeSchool/202302-orleans-php-project-inovin pull request #30
Opened 2023-06-13 11:22 UTC by Mikazian

2023-06-13 13:46 UTC, Zakari-B requested changes

2023-06-13 13:46 UTC, Zakari-B commented on migrations/Version20230613101713.php
> +        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, firstname VARCHAR(25) NOT NULL, lastname VA
Si tu as une notion de "pays" sur l'entité, il vaut mieux ne pas restreindre le code postal à 5 caractères max comme pour la France. Je ne sais pas à quoi ressemblent les CP de l'étranger mais dans le doute... +2d à address

2023-06-13 13:46 UTC, Zakari-B commented on src/DataFixtures/UserFixtures.php
> +        $utilisator->setRoles(['ROLE_UTILISATOR']);
user, pas utilisator

2023-06-13 13:46 UTC, Zakari-B commented on src/Entity/User.php
> +    #[ORM\Column(length: 5, nullable: true)]
Voir mon commentaire précédent quant à la longueur max de cette variable.

2023-06-13 13:46 UTC, Zakari-B commented on src/Entity/User.php
> +    private ?string $adress = null;
address prends 2 d

2023-06-14 12:55 UTC, Abecker37 requested changes

2023-06-14 12:55 UTC, Abecker37 commented on migrations/Version20230613101713.php
je crois que tu ne dois pas avoir plus de 1 class de migration par pr

2023-06-14 12:55 UTC, Abecker37 commented on migrations/Version20230614123826.php
voir le commentaire sur l'autre classe de migration

2023-06-14 13:12 UTC, Abecker37 approved these changes

2023-06-14 14:14 UTC, Zakari-B approved these changes

2023-06-14 14:14 UTC, merged