fin style button link partie cepage
WildCodeSchool/202302-orleans-php-project-inovin pull request #34
Opened 2023-06-14 14:13 UTC by BENJAMIN-SAUSSAYE

2023-06-14 14:17 UTC, No3ml3 approved these changes

2023-06-14 14:17 UTC, Mikazian approved these changes

2023-06-14 14:20 UTC, sblondeau requested changes
si vous charger bootstrap icon via yarn, peut-etre plus besoin de tous ces fichiers svg qui doivent pour la plupart venir de boostrap icon ?

2023-06-15 07:11 UTC, No3ml3 approved these changes

2023-06-15 08:41 UTC, Zakari-B approved these changes

2023-06-15 09:24 UTC, merged