created footer
WildCodeSchool/202302-orleans-php-project-inovin pull request #4
Opened 2023-06-06 13:17 UTC by ElBarto444

2023-06-06 13:45 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-06-06 14:16 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-06-06 14:33 UTC, sblondeau requested changes

2023-06-06 14:33 UTC, sblondeau commented on assets/styles/_footer.scss
> +    font-size: $font-size-mid;
ajoute simplement les classes ps-2 et fs-3 (tu peux ajuster les valeurs) directement dans l'html et ça fera grosso modo pareil

2023-06-06 14:33 UTC, sblondeau commented on assets/styles/_footer.scss
> +    display: flex;
mb-0; d-flex et align-items-center en classe

2023-06-06 14:33 UTC, sblondeau commented on templates/components/_footer.html.twig
> +		<p>© Copyright 2023 | Inovin</p>
cette mention "© Copyright 2023" est inutile 
https://www.tous-droits-reserves.com/origine-mention-tous-droits-reserves.html

2023-06-06 14:33 UTC, sblondeau commented on templates/components/_footer.html.twig
> +		<h3>INO VIN</h3>
pas besoin d'un H3 là, c'est pas vraiment un titre ? ou un h2 au moins car faut respecter la hierarchie des titres

2023-06-06 14:33 UTC, sblondeau commented on templates/components/_footer.html.twig
> +<footer class="d-flex justify-content-around flex-wrap">
je pense que tu utilises pas bien la grid de bootstrap là

plutot que de mettre des d-flex partout, tu devrais utiliser les  row / col

2023-06-07 10:21 UTC, No3ml3 approved these changes

2023-06-07 12:16 UTC, sblondeau approved these changes

2023-06-07 13:31 UTC, merged