integration other data from entity
WildCodeSchool/202302-orleans-php-project-inovin pull request #44
Opened 2023-06-15 15:14 UTC by BENJAMIN-SAUSSAYE

2023-06-15 15:27 UTC, ElBarto444 approved these changes

2023-06-15 15:47 UTC, sblondeau requested changes

2023-06-15 15:47 UTC, sblondeau commented on src/Controller/AdminHomeController.php
>      public function index(AdminDashboardRepository $dashboardRepository, ChartBuilderInterface $chartBuilder): Response
pourquoi un AdminDashboardRepo ? 
L'entité AdminDashboard ne sert à rien

2023-06-15 15:47 UTC, sblondeau commented on src/Repository/AdminDashboardRepository.php
> +
il faut que ces requetes soient splittées, chacune dans le Repository qui la concerne
Et coté controlleur tu va chercher les data de tes 4 repos

2023-06-16 10:30 UTC, Mikazian approved these changes

2023-06-16 14:24 UTC, sblondeau requested changes

2023-06-16 14:24 UTC, sblondeau commented on src/Repository/GrapeVarietyRepository.php
> +            ->from('App\Entity\GrapeVariety', 'g')
le from doit etre inutile

y a aussi https://symfonycasts.com/screencast/doctrine-queries/select-sum#using-getsinglescalarresult qui peut a priori remplacer le COUNT, mais j'ai jamais testé ;-)

2023-06-16 14:24 UTC, sblondeau commented on src/Service/AdminDashboardService.php
> +        return array_merge($grapes, $users, $wines, $sessions);
créé plutot une propriété $data dans ta classe de service, ça simplifiera les choses

2023-06-16 14:24 UTC, sblondeau commented on src/Service/AdminDashboardService.php
> +        foreach ($dashboardData as $key => $value) {
$this->getData() ici du coup par ex

2023-06-17 16:34 UTC, Mikazian approved these changes

2023-06-19 06:51 UTC, sblondeau approved these changes

2023-06-19 06:51 UTC, merged