S3 u19 show opened session
WildCodeSchool/202302-orleans-php-project-inovin pull request #51
Opened 2023-06-19 18:56 UTC by BENJAMIN-SAUSSAYE

2023-06-19 19:08 UTC, No3ml3 approved these changes

2023-06-19 19:42 UTC, sblondeau requested changes

2023-06-19 19:42 UTC, sblondeau commented on assets/styles/session.scss
> +    // background-color: $dark-light;
attention, plein de lignes commentées à enlever

2023-06-19 19:42 UTC, sblondeau commented on migrations/Version20230615081440.php
> +        //$this->addSql('ALTER TABLE wine RENAME INDEX idx_560c646882cc410a TO IDX_560C6468ED00A18A');
code commenté, en dessous aussi

2023-06-19 19:42 UTC, sblondeau commented on templates/components/session/_opened_sessions.html.twig
> +						{% include './components/session/_card_session_grape_variety.html.twig' with { 'wine': wine } %}
le ./ est inutile

2023-06-19 19:42 UTC, sblondeau commented on templates/session/sessions_states_html.twig
> +		{% include './components/session/_opened_sessions.html.twig' with {'sessionsOpened' : sessionsOpened}  %}
le ./ est en trop

sinon je ne comprend pas trop le include à ce niveau
je comprendrais un include pour UNE carde de session, mais là tu créé une page avec juste un "main" dans lequel tu inclus toute une autre page, le niveau du découpage ne me semble pas optimal pour une réutilisation du component ;-)

2023-06-20 14:39 UTC, Mikazian approved these changes

2023-06-20 20:33 UTC, sblondeau approved these changes

2023-06-21 07:44 UTC, No3ml3 approved these changes

2023-06-21 08:46 UTC, merged