Us01 s02 contact form
WildCodeSchool/202302-orleans-php-project-inovin pull request #6
Opened 2023-06-07 09:13 UTC by No3ml3

2023-06-07 12:47 UTC, ElBarto444 approved these changes

2023-06-07 13:44 UTC, sblondeau requested changes

2023-06-07 13:44 UTC, sblondeau commented on assets/styles/contactForm.scss
> +    min-height: 150px!important;
non pas de !important

2023-06-07 13:44 UTC, sblondeau commented on templates/contact/contact.html.twig
> +				<svg class="mb-4 align-self-center" width="190" height="19" viewbox="0 0 190 19" fill="none" xmlns="http://www.w3.org/2000/svg">
hésite ps à mettre les svg dans des fichiers séparé que tu vas include, ça sera plus lisible

2023-06-07 20:14 UTC, Abecker37 requested changes

2023-06-07 20:14 UTC, Abecker37 commented on assets/styles/contactForm.scss
il y a toujours la class bouton

2023-06-08 09:15 UTC, Abecker37 approved these changes

2023-06-08 10:23 UTC, sblondeau approved these changes

2023-06-08 12:39 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-06-08 12:42 UTC, Zakari-B requested changes

2023-06-08 12:42 UTC, Zakari-B commented on src/Entity/Contact.php
> +    public function getSubjet(): string
Subject, pendant qu'on est sur l'orthographe.

2023-06-08 12:42 UTC, Zakari-B commented on src/Form/ContactFormType.php
> +                'attr' => ['placeholder' => 'Veuillez écrire votre sujet'],
"Veuillez renseigner un sujet" me parait moins maladroit.

2023-06-08 12:42 UTC, Zakari-B commented on templates/emailLayout.html.twig
> +    <title>There is news</title>
L'anglais est pas correct, mais de toute manière ça devrait être en français.

2023-06-08 12:42 UTC, Zakari-B commented on config/services.yaml
> -            - "../src/Entity/"
Tu avais un retour d'erreur qui justifiait de le supprimer ?

2023-06-08 12:42 UTC, Zakari-B commented on src/Controller/ContactController.php
> +            $this->addFlash('success', 'Votre email a bien etait envoyé');
Quelqu'un qui ne sait pas conjuger le verbe être.

2023-06-08 12:42 UTC, Zakari-B commented on src/Controller/ContactController.php
> +                ->subject('vous avez un message à propos de ' . $contact->getSubjet())
Début de phrase : majuscule. En plus ça ne fait pas très français cette formulation.

2023-06-08 12:42 UTC, Zakari-B commented on src/Entity/Contact.php
> +    private string $subjet;
subject

2023-06-08 12:50 UTC, No3ml3 commented on config/services.yaml
> -            - "../src/Entity/"
Oui

2023-06-08 13:12 UTC, Zakari-B approved these changes

2023-06-08 13:12 UTC, merged