fin card liste des vins pour les visiteurs
WildCodeSchool/202302-orleans-php-project-inovin pull request #68
Opened 2023-06-21 14:02 UTC by BENJAMIN-SAUSSAYE

liste des vins pour les visiteurs

2023-06-21 14:03 UTC, No3ml3 approved these changes

2023-06-21 14:48 UTC, sblondeau requested changes

2023-06-21 14:48 UTC, sblondeau commented on assets/images/placeholder_wine.svg
4.7M .... je suis pas sur que ce soit le SVG le meilleur format là ?

2023-06-21 14:48 UTC, sblondeau commented on assets/images/line_bolder.svg
c'est moi ou j'ai l'impression d'avoir déjà vu plein  de fois la meme ligne  ? :p

2023-06-21 16:14 UTC, BENJAMIN-SAUSSAYE commented on assets/images/placeholder_wine.svg
Ha oui en jpg ca sera mieux :)

2023-06-21 16:15 UTC, BENJAMIN-SAUSSAYE commented on assets/images/line_bolder.svg
Non, c'est un SVG qui a une hauteur différente, et qui donne une ligne de séparation plus épaisse

2023-06-21 16:16 UTC, BENJAMIN-SAUSSAYE commented on templates/wine/index.html.twig
> +				<div class="col-sm-12 col-11 px-sm-5 px-3 m-auto pt-5 ">
exact du coup j'ai fait une passe sur les autres templates qui avaient la même ligne

2023-06-21 17:04 UTC, No3ml3 approved these changes

2023-06-21 18:58 UTC, sblondeau requested changes

2023-06-21 18:58 UTC, sblondeau commented on templates/wine/index.html.twig
> +				<div class="col-sm-12 col-11 px-sm-5 px-3 m-auto pt-5 ">
mais le col-sm-12 est tjs là ? ;-) 
(et au passage le col-11 ça ressemble à du bricolage non ? :p )

2023-06-22 05:57 UTC, BENJAMIN-SAUSSAYE commented on templates/wine/index.html.twig
> +				<div class="col-sm-12 col-11 px-sm-5 px-3 m-auto pt-5 ">
Desolé j'ai push dans le train hier soir et la connexion n'est pas passé, je pensais les changements push sur github et en fait non ;(

2023-06-22 06:02 UTC, BENJAMIN-SAUSSAYE commented on templates/wine/index.html.twig
> +				<div class="col-sm-12 col-11 px-sm-5 px-3 m-auto pt-5 ">
> 

Oui pas de sans le col-11 je suis d'accord

2023-06-22 07:44 UTC, sblondeau approved these changes

2023-06-22 10:57 UTC, ElBarto444 approved these changes

2023-06-22 11:10 UTC, ElBarto444 approved these changes

2023-06-22 13:55 UTC, merged