S03 us49 password
WildCodeSchool/202302-orleans-php-project-inovin pull request #69
Opened 2023-06-21 15:29 UTC by Mikazian

2023-06-21 15:33 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-06-21 15:33 UTC, ElBarto444 approved these changes

2023-06-22 09:50 UTC, sblondeau requested changes

2023-06-22 09:50 UTC, sblondeau commented on src/Controller/ResetPasswordController.php
> +            throw $this->createNotFoundException('No reset password token found in the URL or in the session.');
traduction

2023-06-22 09:50 UTC, sblondeau commented on src/Form/ResetPasswordRequestFormType.php
> +                        'message' => 'Please enter your email',
traduction

2023-06-22 09:50 UTC, sblondeau commented on src/Controller/ResetPasswordController.php
> +            ->from(new Address('mailer@your-domain.com', 'INOVIN'))
modifier le from, faut pas un email en dur (passer par une variable d'env et un  paramètre)

2023-06-22 13:40 UTC, Abecker37 approved these changes

2023-06-22 13:56 UTC, sblondeau approved these changes

2023-06-22 21:01 UTC, merged