S01US04_home
WildCodeSchool/202302-orleans-php-project-inovin pull request #7
Opened 2023-06-07 14:45 UTC by Abecker37

2023-06-07 16:19 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-06-07 20:29 UTC, sblondeau requested changes
image à réduire <200Ko

2023-06-07 20:29 UTC, sblondeau commented on templates/home/index.html.twig
> +			<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300px"
fais un include pour le svg

2023-06-08 09:01 UTC, No3ml3 approved these changes

2023-06-08 12:42 UTC, closed without merging