ajout du choix de vins dans la partie admin des seances
WildCodeSchool/202302-orleans-php-project-inovin pull request #70
Opened 2023-06-21 15:32 UTC by BENJAMIN-SAUSSAYE

2023-06-21 15:34 UTC, ElBarto444 approved these changes

2023-06-22 09:56 UTC, sblondeau requested changes

2023-06-22 09:56 UTC, sblondeau commented on src/Entity/Wine.php
> +        return $this->getYear() . ' - ' . $this->getName() . ' - ' . $this->getGrapeVariety()->getName();
plutot mettre le name avant la date ? surtout que tu order by name dans le entitytype
et ajouter un order by year en plus du name

2023-06-22 09:56 UTC, sblondeau commented on src/Entity/Wine.php
> +        return $this->getYear() . ' - ' . $this->getName() . ' - ' . $this->getGrapeVariety()->getName();
plutot mettre le name avant la date ? surtout que tu order by name dans le entitytype
et ajouter un order by year en plus du name

2023-06-22 11:09 UTC, BENJAMIN-SAUSSAYE commented on src/Entity/Wine.php
> +        return $this->getYear() . ' - ' . $this->getName() . ' - ' . $this->getGrapeVariety()->getName();
Je n'ai pas ajouté le (order by year) car les résultats sont dans un ordre qui n'arrange pas la lisibilité des infos,

2023-06-22 11:13 UTC, ElBarto444 approved these changes

2023-06-22 13:57 UTC, sblondeau approved these changes

2023-06-22 14:06 UTC, merged