Fix bootstrap jquery
WildCodeSchool/202302-orleans-php-project-inovin pull request #79
Opened 2023-06-22 17:47 UTC by BENJAMIN-SAUSSAYE

2023-06-23 08:32 UTC, No3ml3 approved these changes

2023-06-26 10:21 UTC, sblondeau requested changes

2023-06-26 10:21 UTC, sblondeau commented on assets/app.js
> +);
vraiment utile? vous utilisez des popover ou ?

2023-06-26 10:30 UTC, BENJAMIN-SAUSSAYE commented on assets/app.js
> +);
j'ai retiré les lignes.

2023-06-26 11:14 UTC, Mikazian approved these changes

2023-06-26 12:06 UTC, Zakari-B commented on assets/app.js
> +);
Mais pas push visiblement :)

2023-06-27 15:50 UTC, BENJAMIN-SAUSSAYE commented on assets/app.js
> +);
Ha oui, je pense que c'est dans le train, j'ai dû perdre la connexion ;(

2023-06-28 12:56 UTC, closed without merging