S3 u53 filter wine on index page
WildCodeSchool/202302-orleans-php-project-inovin pull request #82
Opened 2023-06-23 09:49 UTC by BENJAMIN-SAUSSAYE

2023-06-23 12:37 UTC, No3ml3 approved these changes

2023-06-25 14:02 UTC, sblondeau requested changes

2023-06-25 14:02 UTC, sblondeau commented on assets/wine.js
> +        format: {
bon... tu me mets devant le fait accomplit...
- c'est pas une mauvaise idée point de vue UX ce type de double slider (quoi que ça se discute point de vue accessibilité...)
- mais c'est pas le plus simple à mettre en place, je ne connais pas la lib donc je pars du principe que ça marche bien
- tu aurais pu faire avec 2 input tout simplement ça aurait fait amplement l'affaire
=> hésite pas à me consulter avant de te lancer dans l'utilisation de lib externe. Car ça te fait perdre du temps et peut-etre que ce n'est pas ce que le client souhaite

Et pour la relecture de la PR, j'ai 16 fichiers, c'est bien trop. 6 ou 7 fichiers en moins si tu n'implémentes pas le JS, donc ça prend plus de temps à valider car faut que je prenne plus de temps, que je passe un peu de temps à pester "Benjamin fait encore trop compliqué" ...  ;-) 

Donc sur le fond je ne dis pas que c'est une mauvaise idée, c'est meme plutot cool si ça fonctionne bien, mais dans la démarche, ça doit être découpé au moins en 2US...
Et fais moi valider l'idée avant. Je ne veux pas vous restreindre techniquement mais je ne veux pas que vous perdiez du temps sur du non essentiel. Et la on perd du temps car des US comme ça seront toujours bien plus longue à passer que 2 petites !

2023-06-26 09:37 UTC, BENJAMIN-SAUSSAYE commented on templates/wine/index.html.twig
> +							<div class="collapse" id="collapseSearch">
oui c'est ca

2023-06-26 09:44 UTC, BENJAMIN-SAUSSAYE commented on assets/app.js
> +);
C'était recommandé dans la doc boostrap 5.3 :

https://getbootstrap.com/docs/5.3/components/popovers/

J'ai fait un test sans les lignes, cela semble fonctionner donc je ne sais pas trop quoi en penser, du coup, j'ai supprimé les lignes en question

2023-06-26 09:45 UTC, BENJAMIN-SAUSSAYE commented on assets/wine.js
> +        format: {
ok

2023-06-26 11:13 UTC, Mikazian approved these changes

2023-06-27 11:19 UTC, sblondeau commented
tu es sur que tu as push ? je vois pas les modifs ;-)

2023-06-27 15:57 UTC, BENJAMIN-SAUSSAYE commented
> tu es sur que tu as push ? je vois pas les modifs ;-)

J'ai l'impression que le push n'est pas passé ;(

2023-06-30 10:10 UTC, sblondeau approved these changes

2023-06-30 10:10 UTC, merged