S04 us33 edit recipe
WildCodeSchool/202302-orleans-php-project-inovin pull request #91
Opened 2023-06-26 12:35 UTC by Abecker37

2023-06-26 12:38 UTC, ElBarto444 approved these changes

2023-06-27 11:24 UTC, sblondeau requested changes

2023-06-27 11:24 UTC, sblondeau commented on src/Entity/Recipe.php
> +    #[Assert\Type('integer')]
min et max ?

2023-06-27 11:24 UTC, sblondeau commented on src/Form/RecipeType.php
> +                        'placeholder' => '14',
min et max

2023-06-27 11:24 UTC, sblondeau commented on src/Form/RecipeType.php
> +                        'placeholder' => 'Thomas',
c'est pas parlant comme placehoder de nom de recette de mettre un prénom

2023-06-27 13:45 UTC, No3ml3 approved these changes

2023-06-27 13:52 UTC, sblondeau approved these changes

2023-06-27 13:52 UTC, merged